# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f52e2acfbbe1adcc9c922e7e96bc73a402be56c3b62f95dd4833add325ee41546448dee88ac487ae21f5d92eeada623f368acb47ba4b462348261163b26ea437

test:
  secret_key_base: 211c01fcdee3c3e9fa472211b29c0877994215d0850d9d9cc82a1da114929b2e1984d75a769bf117126a88ea1c7af172ca7049f8409e3251ed8237d5aeb3119c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
